site_name: 招生指北
theme:
  name: material
  features:
    - navigation.tabs
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: zh
nav:
  - 主页: index.md
  - 北京大学:
      - 胡阅 北京大学考古文博学院 23: PKU/HY.md
      - 韩奇晔  北京大学医学部基础医学院基础医学专业 23: PKU/HQY.md
  - About: about.md