site_name: 招生指北
site_url: https://zszb.github.io/
theme:
  name: material
  logo: 1.png
  features:
    #- navigation.tabs
    - search.highlight
    - search.suggest
    - navigation.indexes
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: zh  
copyright: Copyright &copy; 2023-2025 招生指北
repo_url: https://github.com/fxd05/zszb.github.io
repo_name: zszb.github.io
markdown_extensions: 
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - 主页: index.md
  - 北京大学:
    - 胡同学 北京大学考古文博学院 23: PKU/HY.md
    - 韩同学  北京大学医学部基础医学院基础医学专业 23: PKU/HQY.md
    - 沈同学 北京大学医学部 基础医学院 临床医学八年制专业 24: PKU/SNQ.md
  - 清华大学:
    - 刘同学 清华大学行健书院 理论与应用力学+土木水利与海洋工程 23: THU/LYY.md
    - 方同学 清华大学未央书院 数理基础科学+能源与动力工程 23: THU/FBH.md
  - 中国科学院大学:
    - 潘同学 中国科学院大学人工智能学院 23: UCAS/PTL.md
  - 浙江大学:
    - 人文社科类: 
      - 叶同学 浙江大学工商管理专业三一录取 23: ZJU/W/YRH.md
      - 谢同学 浙江大学外国语言文学类翻译专业→社会学 23: ZJU/W/XFY.md
      - 徐同学 浙江大学社会科学试验班分流财政学 23: ZJU/W/XJS.md
      - 顾同学 浙江大学智能财务荣誉项目班 23: ZJU/W/GZQ.md
      - 褚同学 浙江大学社会学 三一 23: ZJU/W/CXY.md
      - 褚同学 浙江大学社会科学试验班 分流至会计学 24: ZJU/W/CYY.md
    - 偏理工科类:
      - 汪同学 浙江大学数字金融（俗称数学金融学双学位项目） 23: ZJU/L/WYH.md
      - 鲁同学 浙江大学数字金融 23: ZJU/L/LS.md 
      - 鲍同学 浙江大学机械工程 23: ZJU/L/BWC.md
      - 徐同学 浙江大学心理学 23: ZJU/L/XCZ.md
      - 汪同学 浙江大学自动化（控制） 23: ZJU/L/WCY.md
      - 邵同学 浙江大学医学试验班（临床八年制）——俗称巴德年班 24: ZJU/L/SW.md
      - 方同学 浙江大学工科试验班(竺可桢学院图灵班) 24: ZJU/L/FWC.md
  - 上海交通大学:
    - 王同学 上海交通大学IEEE试点班 23: SJTU/WXR.md
    - 夏同学 上海交通大学 化学(致远计划) 23: SJTU/XJL.md
    - 曾同学 上海交通大学核工程与核技术 23: SJTU/ZBY.md
  - 复旦大学:
    - 郑同学 复旦大学 数学 23: FDU/ZGH.md
    - 俞同学 复旦大学临床医学八年制 23: FDU/YBY.md
    - 孙同学 复旦大学新闻学院 23: FDU/SJY.md
    - 鲁同学 复旦大学 公共卫生学院公共事业管理 24: FDU/LXW.md
  - 武汉大学:
    - 施同学 武汉大学 口腔医学-->法学 23: WHU/SXY.md
  - 哈尔滨医科大学:
    - 林同学 哈尔滨医科大学 智能医学工程: HRBMU/LTA.md
  - 中央民族大学:
    - 胡同学 中央民族大学 历史学: MUC/HJX.md
  - 中国科学技术大学:
    - 叶同学 中国科学技术大学 网络空间安全专业: USTC/YLT.md
  - 厦门大学:
    - 诸同学 厦门大学 经济学院经济学类 24: XMU/ZSY.md
  - 帝国理工:
    - 张同学 帝国理工 计算机 23: ILC/ZYK.md
  - 中国人民大学: RUC/RUC.md
      